### 학습목표
- pandas 라이브러리를 마스터할 수 있다!!
- 인덱싱, 슬라이싱, 행추가, 열추가, 연산 등에 대한 모든 정보를 마스터할 수 있다!!

##### 개념정리
- 인덱싱, 슬라이싱
  - 데이터에 범위를 주어 원하는 데이터를 추출
  - 열인덱싱 -> df['컬럼명']
  - 행슬라이싱 -> df[행번위]
  - 행과 열 단위로 추출 -> 인덱서 (loc,iloc)
    - df.loc[행범위,열범위] => 인덱스명
    - do.iloc[행범위,열범위] => 인덱스번호

In [1]:
import pandas as pd

In [2]:
population = pd.read_csv('./data/population.csv', index_col = '도시')
population

     지역     2020        2015        2010      2005
도시
서울  수도권  9668465  10022181.0  10312545.0  10167344
부산  경상권  3391946         NaN         NaN   3628293
인천  수도권  2942828   2925815.0         NaN   2600495
광주  전라권  1450062   1474636.0   1454636.0   1401745
대구  경상권  2418436   2466052.0   2431774.0   2456016

In [3]:
#1. 서울~인천, 2020~2010 데이터를 추출
population.loc['서울':'인천','2020':'2010']

       2020        2015        2010
도시
서울  9668465  10022181.0  10312545.0
부산  3391946         NaN         NaN
인천  2942828   2925815.0         NaN

In [4]:
population.iloc[0:3,1:4]

       2020        2015        2010
도시
서울  9668465  10022181.0  10312545.0
부산  3391946         NaN         NaN
인천  2942828   2925815.0         NaN

- 불리언 인덱싱
  - 조건을 활용하여 조건식이 True인 데이터를 출력
  - df[조건]

In [5]:
#2020년에 인구가 2,000,000 이상인 도시를 출력
population[population['2020']>=2000000]

     지역     2020        2015        2010      2005
도시
서울  수도권  9668465  10022181.0  10312545.0  10167344
부산  경상권  3391946         NaN         NaN   3628293
인천  수도권  2942828   2925815.0         NaN   2600495
대구  경상권  2418436   2466052.0   2431774.0   2456016

In [6]:
#2020년에 인구가 2,000,000 이상인 도시 이름만 출력
population[population['2020']>=2000000].index

Index(['서울', '부산', '인천', '대구'], dtype='object', name='도시')

In [7]:
#2020년에 인구가 2,000,000 이상인 도시dml 2020년도 인구 출력
population[population['2020']>=2000000]['2020']

도시
서울    9668465
부산    3391946
인천    2942828
대구    2418436
Name: 2020, dtype: int64

In [8]:
#열추가
#df[추가할 컬럼명]=[데이터]

population['2000']=[0,0,0,0,0]
population

     지역     2020        2015        2010      2005  2000
도시
서울  수도권  9668465  10022181.0  10312545.0  10167344     0
부산  경상권  3391946         NaN         NaN   3628293     0
인천  수도권  2942828   2925815.0         NaN   2600495     0
광주  전라권  1450062   1474636.0   1454636.0   1401745     0
대구  경상권  2418436   2466052.0   2431774.0   2456016     0

In [9]:
# 행추가 -> 순천 행 추가
population.loc['순천'] = ['전라권',0,0,0,0,0]
population

     지역     2020        2015        2010      2005  2000
도시
서울  수도권  9668465  10022181.0  10312545.0  10167344     0
부산  경상권  3391946         NaN         NaN   3628293     0
인천  수도권  2942828   2925815.0         NaN   2600495     0
광주  전라권  1450062   1474636.0   1454636.0   1401745     0
대구  경상권  2418436   2466052.0   2431774.0   2456016     0
순천  전라권        0         0.0         0.0         0     0

In [10]:
# 결측치(NaN)를 원하는 값으로 바꿔주는 함수
# 결측치끼리의 연산은 결측치로 출력되기 때문!!
# df명.fillna(value = 특정값)
population.fillna(value=0, inplace=True)
population

     지역     2020        2015        2010      2005  2000
도시
서울  수도권  9668465  10022181.0  10312545.0  10167344     0
부산  경상권  3391946         0.0         0.0   3628293     0
인천  수도권  2942828   2925815.0         0.0   2600495     0
광주  전라권  1450062   1474636.0   1454636.0   1401745     0
대구  경상권  2418436   2466052.0   2431774.0   2456016     0
순천  전라권        0         0.0         0.0         0     0

### DataFrame 실습

In [11]:
score = pd.read_csv('./data/score.csv', encoding = 'euc-kr', index_col= '과목')
score

     1반  2반  3반  4반
과목
파이썬  45  44  73  39
DB   76  92  45  69
자바   47  92  45  69
크롤링  92  81  85  40
Web  11  79  47  26

Q1. 과목별 합계를 구하여 DataFrame에 추가('합계'컬럼 추가)

In [12]:
# 과목별 합계 -> 열방향연산 -> 축설정 axis = 1 
score['합계']=score.sum(axis=1)

In [13]:
score

     1반  2반  3반  4반   합계
과목
파이썬  45  44  73  39  201
DB   76  92  45  69  282
자바   47  92  45  69  253
크롤링  92  81  85  40  298
Web  11  79  47  26  163

Q2. 과목별 평균을 계산하여 '평균'컬럼 추가

In [14]:
score['평균']=score.iloc[:,0:-1].mean(axis=1)
score

     1반  2반  3반  4반   합계     평균
과목
파이썬  45  44  73  39  201  50.25
DB   76  92  45  69  282  70.50
자바   47  92  45  69  253  63.25
크롤링  92  81  85  40  298  74.50
Web  11  79  47  26  163  40.75

Q3. 반별 평균을 계산하여 "반평균" 행 추가

In [15]:
score.iloc[:,:-1].mean()

1반     54.2
2반     77.6
3반     59.0
4반     48.6
합계    239.4
dtype: float64

In [16]:
score.loc['반평균']=score.iloc[:,:-1].mean()

In [19]:
score.fillna(value='-', inplace=True)

C:\Users\Park_kunbeom\AppData\Local\Temp\ipykernel_21496\2844178756.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '-' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  score.fillna(value='-', inplace=True)

In [20]:
score

       1반    2반    3반    4반     합계     평균
과목
파이썬  45.0  44.0  73.0  39.0  201.0  50.25
DB   76.0  92.0  45.0  69.0  282.0   70.5
자바   47.0  92.0  45.0  69.0  253.0  63.25
크롤링  92.0  81.0  85.0  40.0  298.0   74.5
Web  11.0  79.0  47.0  26.0  163.0  40.75
반평균  54.2  77.6  59.0  48.6  239.4      -